package catalog

// x-utf8MaxBytes is the v2 byte assertion; maxLength remains the standard
// code-point prefilter, and the strict runtime validator will enforce this cap.
const setCWDInputSchema = `{"type":"object","properties":{"directory":{"type":"string","minLength":1,"maxLength":4096,"x-utf8MaxBytes":4096,"pattern":"^(/|[A-Za-z]:[\\\\/]).*","description":"Absolute local directory; 1..4096 UTF-8 bytes."}},"required":["directory"],"additionalProperties":false}`

const projectInputSchema = `{"oneOf":[{"type":"object","properties":{"cwd_id":{"type":"integer","minimum":1,"maximum":9007199254740991,"description":"Registered cwd_id."},"path":{"type":"string","minLength":1,"maxLength":4096,"x-utf8MaxBytes":4096,"default":".","description":"Relative subtree root; 1..4096 UTF-8 bytes."},"depth":{"type":"integer","minimum":0,"maximum":8,"default":2,"description":"Maximum traversal depth."},"limit":{"type":"integer","minimum":1,"maximum":1000,"default":200,"description":"Maximum result rows."},"include_ignored":{"type":"boolean","default":false,"description":"Include ordinary ignored directories."}},"required":["cwd_id"],"additionalProperties":false},{"type":"object","properties":{"cwd_id":{"type":"integer","minimum":1,"maximum":9007199254740991,"description":"Registered cwd_id."},"cursor":{"type":"string","minLength":22,"maxLength":22,"pattern":"^[A-Za-z0-9_-]{22}$","description":"Opaque 22-character continuation token."}},"required":["cwd_id","cursor"],"additionalProperties":false}]}`

const searchInputSchema = `{"oneOf":[{"type":"object","properties":{"cwd_id":{"type":"integer","minimum":1,"maximum":9007199254740991,"description":"Registered cwd_id."},"query":{"type":"string","minLength":1,"maxLength":4096,"x-utf8MaxBytes":4096,"description":"Search expression; 1..4096 UTF-8 bytes."},"mode":{"type":"string","enum":["file","text","symbol"],"default":"text","description":"Search family."},"path":{"type":"string","minLength":1,"maxLength":4096,"x-utf8MaxBytes":4096,"default":".","description":"Relative search root; 1..4096 UTF-8 bytes."},"glob":{"type":"string","minLength":1,"maxLength":4096,"x-utf8MaxBytes":4096,"description":"Optional file glob for text or symbol mode; 1..4096 UTF-8 bytes."},"regex":{"type":"boolean","default":false,"description":"Interpret text or symbol query as RE2; omit in file mode."},"ignore_case":{"type":"boolean","default":false,"description":"Use Unicode case-fold matching."},"context":{"type":"integer","minimum":0,"maximum":20,"default":0,"description":"Context lines for text mode; omit in file or symbol mode."},"include_ignored":{"type":"boolean","default":false,"description":"Include ordinary ignored directories."},"limit":{"type":"integer","minimum":1,"maximum":1000,"default":50,"description":"Maximum result rows."}},"required":["cwd_id","query"],"additionalProperties":false},{"type":"object","properties":{"cwd_id":{"type":"integer","minimum":1,"maximum":9007199254740991,"description":"Registered cwd_id."},"cursor":{"type":"string","minLength":22,"maxLength":22,"pattern":"^[A-Za-z0-9_-]{22}$","description":"Opaque 22-character continuation token."}},"required":["cwd_id","cursor"],"additionalProperties":false}]}`

const readInputSchema = `{"oneOf":[{"type":"object","properties":{"cwd_id":{"type":"integer","minimum":1,"maximum":9007199254740991,"description":"Registered cwd_id."},"files":{"type":"array","minItems":1,"maxItems":24,"description":"Files to read.","items":{"type":"object","properties":{"path":{"type":"string","minLength":1,"maxLength":4096,"x-utf8MaxBytes":4096,"description":"Relative file path; 1..4096 UTF-8 bytes."},"start":{"type":"integer","minimum":1,"maximum":2147483647,"default":1,"description":"First source line; source view only."},"end":{"type":"integer","minimum":1,"maximum":2147483647,"description":"Last source line; required for source view and omitted for outline."}},"required":["path"],"additionalProperties":false}},"view":{"type":"string","enum":["source","outline"],"default":"source","description":"Output representation."},"max_bytes":{"type":"integer","minimum":4096,"maximum":1048576,"default":1048576,"description":"Maximum aggregate TextContent bytes."}},"required":["cwd_id","files"],"additionalProperties":false},{"type":"object","properties":{"cwd_id":{"type":"integer","minimum":1,"maximum":9007199254740991,"description":"Registered cwd_id."},"cursor":{"type":"string","minLength":22,"maxLength":22,"pattern":"^[A-Za-z0-9_-]{22}$","description":"Opaque 22-character continuation token."}},"required":["cwd_id","cursor"],"additionalProperties":false}]}`
